name: CI

on:
  push:
    branches:
      - main
      - develop
      - feature_*
  pull_request:
    branches:
      - main
      - develop
      - feature_*

jobs:
  tests:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Code checkout
        uses: actions/checkout@v2

      - name: Build
        run: go build

      - name: Test
        run: |
          sudo iptables -P FORWARD ACCEPT 
          sudo env "PATH=$PATH" go test $(go list ./... | grep -v "/runner") -p=1 -failfast -v -coverprofile=coverage.out -covermode=atomic
          sudo chmod 666 coverage.out

      - name: Code coverage
        run: bash <(curl -s https://codecov.io/bash)

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
